# Generated by Django 4.1.2 on 2022-12-06 04:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('avgPEStr', models.CharField(default='', max_length=255)),
                ('avgMarketValueStr', models.CharField(default='', max_length=255)),
                ('avgYieldStr', models.CharField(default='', max_length=255)),
                ('avgROEStr', models.CharField(default='', max_length=255)),
                ('avgEPSStr', models.CharField(default='', max_length=255)),
                ('avgGrossMarginStr', models.CharField(default='', max_length=255)),
                ('avgDebtAssetRatioStr', models.CharField(default='', max_length=255)),
                ('avgEPSGrowthRate5YearsStr', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Index',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_code', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('stockIndustry', models.CharField(default='', max_length=255)),
                ('stockFullName', models.CharField(default='', max_length=255)),
                ('stockAddress', models.CharField(default='', max_length=255)),
                ('stockChairman', models.CharField(default='', max_length=255)),
                ('stockManager', models.CharField(default='', max_length=255)),
                ('stockMainBusiness', models.TextField(default='')),
                ('stockCreatedDate', models.CharField(default='', max_length=255)),
                ('stockCapital', models.CharField(default='', max_length=255)),
                ('stockIPODate', models.CharField(default='', max_length=255)),
                ('stockState', models.CharField(default='', max_length=255)),
                ('stockCommonSharePrice', models.CharField(default='', max_length=255)),
                ('stockCommonShares', models.CharField(default='', max_length=255)),
                ('stockDividendFrequency', models.CharField(default='', max_length=255, null=True)),
                ('stockCompanyURL', models.CharField(default='', max_length=255, null=True)),
                ('stockMoneyDJIntroduceURL', models.CharField(default='', max_length=255, null=True)),
                ('stockCompanyIntroduceURL', models.CharField(default='', max_length=255, null=True)),
                ('stockConpanyInvestorURL', models.CharField(default='', max_length=255, null=True)),
                ('stockCompanyAnnualReportURL', models.CharField(default='', max_length=255, null=True)),
                ('stockCompanySeasonFinancialReportURL', models.CharField(default='', max_length=255, null=True)),
                ('financialReportStartDate', models.CharField(default='', max_length=255)),
                ('annualReportStartDate', models.CharField(default='', max_length=255)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stockCore.category')),
            ],
        ),
        migrations.CreateModel(
            name='StockRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('OpeningPrice', models.DecimalField(decimal_places=2, max_digits=7)),
                ('ClosingPrice', models.DecimalField(decimal_places=2, max_digits=7)),
                ('DayHigh', models.DecimalField(decimal_places=2, max_digits=7)),
                ('DayLow', models.DecimalField(decimal_places=2, max_digits=7)),
                ('Volume', models.DecimalField(decimal_places=0, max_digits=13)),
                ('Transaction', models.IntegerField()),
                ('TurnOver', models.DecimalField(decimal_places=0, max_digits=14)),
                ('Dir', models.CharField(max_length=255)),
                ('Change', models.DecimalField(decimal_places=2, max_digits=6)),
                ('FinalBuyPrice', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('FinalBuyVolume', models.IntegerField(default=0)),
                ('FinalSellPrice', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('FinalSellVolume', models.IntegerField(default=0)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stockCore.stock')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='index',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stockCore.index'),
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('fb_id', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('google_id', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('apple_id', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('line_id', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
