# Generated by Django 4.1.2 on 2022-12-09 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stockCore', '0005_userstock_userstocktrade_stockdayrecommend'),
    ]

    operations = [
        migrations.CreateModel(
            name='KbarsType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, choices=[('0', 'ChildParent'), ('1', 'LongShadeLine')], max_length=100, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='stockdayrecommend',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stockCore.kbarstype'),
        ),
    ]
