# Generated by Django 4.1.2 on 2022-12-09 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockCore', '0007_rename_price_userstocktrade_sell_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockrecord',
            name='MA_10',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='stockrecord',
            name='MA_20',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='stockrecord',
            name='MA_5',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
    ]
