# Generated by Django 4.1.2 on 2022-12-09 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockCore', '0008_stockrecord_ma_10_stockrecord_ma_20_stockrecord_ma_5'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockrecord',
            old_name='MA_10',
            new_name='MA_l',
        ),
        migrations.RenameField(
            model_name='stockrecord',
            old_name='MA_20',
            new_name='MA_m',
        ),
        migrations.RenameField(
            model_name='stockrecord',
            old_name='MA_5',
            new_name='MA_s',
        ),
    ]
