# Generated by Django 4.1.2 on 2022-12-09 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockCore', '0009_rename_ma_10_stockrecord_ma_l_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kbarstype',
            name='name',
            field=models.CharField(blank=True, choices=[('1', 'ChildParent'), ('2', 'LongShadeLine')], max_length=100, null=True),
        ),
    ]
