# Generated by Django 4.1.2 on 2022-12-10 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockCore', '0010_alter_kbarstype_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kbarstype',
            name='name',
            field=models.CharField(blank=True, choices=[('1', 'ChildParent'), ('2', 'LongShadeLine'), ('3', 'N_type')], max_length=100, null=True),
        ),
    ]
