# Generated by Django 4.1.2 on 2022-12-10 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stockCore', '0011_alter_kbarstype_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='N_Font_Type_Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Early_Stage_start_at', models.DateField()),
                ('Early_Stage_start_price', models.DecimalField(decimal_places=2, max_digits=13)),
                ('Early_Stage_high_price', models.DecimalField(decimal_places=2, max_digits=13)),
                ('Early_Stage_correction_start_at', models.DateField()),
                ('Early_Stage_correction_low_price', models.DecimalField(decimal_places=2, max_digits=13)),
                ('Primary_Stage_start_at', models.DateField()),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stockCore.stock')),
            ],
        ),
    ]
