# Generated by Django 4.1.2 on 2022-12-10 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockCore', '0012_n_font_type_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='n_font_type_stock',
            name='Early_Stage_correction_low_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='n_font_type_stock',
            name='Early_Stage_correction_start_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='n_font_type_stock',
            name='Early_Stage_high_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='n_font_type_stock',
            name='Early_Stage_start_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='n_font_type_stock',
            name='Primary_Stage_start_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
