# Generated by Django 4.1.2 on 2022-12-10 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockCore', '0013_alter_n_font_type_stock_early_stage_correction_low_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockrecord',
            name='MA_l',
        ),
        migrations.RemoveField(
            model_name='stockrecord',
            name='MA_m',
        ),
        migrations.RemoveField(
            model_name='stockrecord',
            name='MA_s',
        ),
        migrations.AddField(
            model_name='user',
            name='PERSON_ID',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='account_password',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
