# Generated by Django 4.1.2 on 2022-12-22 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockCore', '0014_remove_stockrecord_ma_l_remove_stockrecord_ma_m_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockrecord',
            name='DIF',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='stockrecord',
            name='EMA_12',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='stockrecord',
            name='EMA_26',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='stockrecord',
            name='MACD',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
    ]
