# Generated by Django 4.1.2 on 2022-12-27 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockCore', '0016_n_font_type_stock_red_sign_start_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kbarstype',
            name='name',
            field=models.CharField(blank=True, choices=[('1', 'ChildParent'), ('2', 'LongShadeLine'), ('3', 'N_type'), ('4', 'Red_sign')], max_length=100, null=True),
        ),
    ]
