# Generated by Django 4.1.2 on 2023-03-30 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockCore', '0017_alter_kbarstype_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockrecord',
            name='Signal',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
