# Generated by Django 4.1.7 on 2023-03-31 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockCore', '0018_stockrecord_signal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kbarstype',
            name='name',
            field=models.CharField(blank=True, choices=[('1', 'ChildParent'), ('2', 'LongShadeLine'), ('3', 'N_type'), ('4', 'Red_sign'), ('5', 'Model_Predict')], max_length=100, null=True),
        ),
    ]
