# Generated by Django 4.1.2 on 2023-04-02 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockCore', '0019_alter_kbarstype_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='PERSON_ID',
            new_name='API_Key',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='account_password',
            new_name='Secret_Key',
        ),
    ]
