from celery import shared_task
from bs4 import BeautifulSoup
import requests

#not use
@shared_task
def crawl_stock_child_companies():
    resp = requests.get("https://mops.twse.com.tw/mops/web/t79sb02?encodeURIComponent=1&step=1&firstin=1&off=1&keyword4=&code1=&TYPEK2=&checkbtn=&queryName=co_id&inpuType=co_id&TYPEK=all&co_id=2330")
    soup = BeautifulSoup(resp.text, 'html.parser')

    info = soup.find_all("table", {"class": "hasBorder"})[0]
    childs = info.find_all('tr')
    childs.pop(0)

    for childStock in childs:
        print("日期"  + childStock.find_all("td")[0].string )
        print("重要子公司名稱" + childStock.find_all("td")[1].string )
        print("主要經營業務" + childStock.find_all("td")[2].string )
        print("地區	" + childStock.find_all("td")[3].string )
        print("符合重要子公司認定之標準(註)" + childStock.find_all("td")[4].string )

#not use
@shared_task
def crawl_statement_of_changes_in_equity():
    resp = requests.get('https://mops.twse.com.tw/mops/web/t164sb06?encodeURIComponent=1&step=1&firstin=1&off=1&keyword4=&code1=&TYPEK2=&checkbtn=&queryName=co_id&inpuType=co_id&TYPEK=all&isnew=false&co_id=2330&year=110&season=01')
    soup = BeautifulSoup(resp.text, 'html.parser')

    print(soup.find_all('font',{'color':'blue'})[0].getText())
    #標題
    print(soup.find_all('font',{'color':'blue'})[1].getText())
    #資料來源
    print(soup.find_all('b')[0].getText())

    tables = soup.find_all('table',{'class':'hasBorder'})
    table1 = soup.find_all('table',{'class':'hasBorder'})[0]
    table2 = soup.find_all('table',{'class':'hasBorder'})[1]

    print(soup.find_all('th',{'class':'tblHead'})[0].getText())
    print(soup.find_all('th',{'class':'tblHead'})[1].getText())
    trs1 = table1.find_all('tr')
    for item in trs1[3:]:
        print(item.find_all('td')[0].getText())
        print('普通股股本'+ item.find_all('td')[1].getText().replace(' ',''))
        print('股本合計'+ item.find_all('td')[2].getText().replace(' ',''))
        print('資本公積'+ item.find_all('td')[3].getText().replace(' ',''))
        print('法定盈餘公積'+ item.find_all('td')[4].getText().replace(' ',''))
        print('特別盈餘公積'+ item.find_all('td')[5].getText().replace(' ',''))
        print('未分配盈餘（或待彌補虧損）'+ item.find_all('td')[6].getText().replace(' ',''))
        print('保留盈餘合計'+ item.find_all('td')[7].getText().replace(' ',''))
        print('國外營運機構財務報表換算之兌換差額'+ item.find_all('td')[8].getText().replace(' ',''))
        print('透過其他綜合損益按公允價值衡量之金融資產未實現評價(損)益'+ item.find_all('td')[9].getText().replace(' ',''))
        print('避險工具之利益（損失）'+ item.find_all('td')[10].getText().replace(' ',''))
        print('其他'+ item.find_all('td')[11].getText().replace(' ',''))
        print('其他權益項目合計'+ item.find_all('td')[12].getText().replace(' ',''))
        print('庫藏股票'+ item.find_all('td')[13].getText().replace(' ',''))
        print('歸屬於母公司業主之權益總計'+ item.find_all('td')[14].getText().replace(' ',''))
        print('非控制權益'+ item.find_all('td')[15].getText().replace(' ',''))
        print('權益總額'+ item.find_all('td')[16].getText().replace(' ',''))


    print(soup.find_all('th',{'class':'tblHead'})[3].getText())
    print(soup.find_all('th',{'class':'tblHead'})[4].getText())
    trs2 = table2.find_all('tr')
    for item in trs2[3:]:
        print(item.find_all('td')[0].getText())
        print('普通股股本'+ item.find_all('td')[1].getText().replace(' ',''))
        print('股本合計'+ item.find_all('td')[2].getText().replace(' ',''))
        print('資本公積'+ item.find_all('td')[3].getText().replace(' ',''))
        print('法定盈餘公積'+ item.find_all('td')[4].getText().replace(' ',''))
        print('特別盈餘公積'+ item.find_all('td')[5].getText().replace(' ',''))
        print('未分配盈餘（或待彌補虧損）'+ item.find_all('td')[6].getText().replace(' ',''))
        print('保留盈餘合計'+ item.find_all('td')[7].getText().replace(' ',''))
        print('國外營運機構財務報表換算之兌換差額'+ item.find_all('td')[8].getText().replace(' ',''))
        print('透過其他綜合損益按公允價值衡量之金融資產未實現評價(損)益'+ item.find_all('td')[9].getText().replace(' ',''))
        print('避險工具之利益（損失）'+ item.find_all('td')[10].getText().replace(' ',''))
        print('其他'+ item.find_all('td')[11].getText().replace(' ',''))
        print('其他權益項目合計'+ item.find_all('td')[12].getText().replace(' ',''))
        print('庫藏股票'+ item.find_all('td')[13].getText().replace(' ',''))
        print('歸屬於母公司業主之權益總計'+ item.find_all('td')[14].getText().replace(' ',''))
        print('非控制權益'+ item.find_all('td')[15].getText().replace(' ',''))
        print('權益總額'+ item.find_all('td')[16].getText().replace(' ',''))

#not use
@shared_task
def crawl_dividend_distribution():
    resp = requests.get('https://mops.twse.com.tw/mops/web/t05st09_2?encodeURIComponent=1&step=1&firstin=1&off=1&keyword4=&code1=&TYPEK2=&checkbtn=&queryName=co_id&inpuType=co_id&TYPEK=all&isnew=false&co_id=2330&date1=100&date2=110&qryType=1')
    soup = BeautifulSoup(resp.text, 'html.parser')
    print(soup.find_all('b')[0].getText())
    print(soup.find_all('b')[1].getText().replace(' ',''))

    table = soup.find_all('table',{'class':'hasBorder'})[0]
    info = table.find_all('tr')
    for item in info[3:]:
        print('決議（擬議）進度'+item.find_all('td')[0].getText())
        print('股利所屬年(季)度'+item.find_all('td')[1].getText())
        print('股利所屬期間'+item.find_all('td')[2].getText())
        print('期別'+item.find_all('td')[3].getText())
        print('董事會決議(擬議)股利分派日'+item.find_all('td')[4].getText())
        print('股東會日期'+item.find_all('td')[5].getText())
        print('期初未分配盈餘/待彌補虧損(元)'+item.find_all('td')[6].getText())
        print('本期淨利(淨損)(元)'+item.find_all('td')[7].getText())
        print('可分配盈餘(元)'+item.find_all('td')[8].getText())
        print('分配後期末未分配盈餘(元)'+item.find_all('td')[9].getText())
        print('盈餘分配之現金股利(元/股)'+item.find_all('td')[10].getText())
        print('法定盈餘公積發放之現金(元/股)'+item.find_all('td')[11].getText())
        print('資本公積發放之現金(元/股)'+item.find_all('td')[12].getText())
        print('股東配發之現金(股利)總金額(元)'+item.find_all('td')[13].getText())
        print('盈餘轉增資配股(元/股)'+item.find_all('td')[14].getText())
        print('法定盈餘公積轉增資配股(元/股)'+item.find_all('td')[15].getText())
        print('資本公積轉增資配股(元/股)'+item.find_all('td')[16].getText())
        print('股東配股總股數(股)'+item.find_all('td')[17].getText())
        print('備註'+item.find_all('td')[19].getText())
        print('普通股每股面額'+item.find_all('td')[20].getText())

    print(soup.find_all('p',{'align':'left'})[0].getText())
    print(soup.find_all('p',{'align':'left'})[1].getText())
    print(soup.find_all('p',{'align':'left'})[2].getText())

#not use
@shared_task
def crawl_all_income_sheet():
    resp = requests.get('https://mops.twse.com.tw/mops/web/t163sb04?encodeURIComponent=1&step=1&firstin=1&off=1&isQuery=Y&TYPEK=sii&year=110&season=01')
    soup = BeautifulSoup(resp.text, 'html.parser')
    print(soup.find_all('h2')[0].getText())

    tables = soup.find_all('table',{'class':'hasBorder'})
    trs1 = tables[0].find_all('tr')
    for item in trs1[1:]:
        print('公司代號'+item.find_all('td')[0].getText())
        print('公司名稱'+item.find_all('td')[1].getText())
        print('利息淨收益'+item.find_all('td')[2].getText())
        print('利息以外淨損益'+item.find_all('td')[3].getText())
        print('呆帳費用、承諾及保證責任準備提存'+item.find_all('td')[4].getText())
        print('營業費用'+item.find_all('td')[5].getText())
        print('繼續營業單位稅前淨利（淨損）'+item.find_all('td')[6].getText())
        print('所得稅費用（利益）'+item.find_all('td')[7].getText())
        print('繼續營業單位本期稅後淨利（淨損）'+item.find_all('td')[8].getText())
        print('停業單位損益'+item.find_all('td')[9].getText())
        print('合併前非屬共同控制股權損益'+item.find_all('td')[10].getText())
        print('本期稅後淨利（淨損）'+item.find_all('td')[11].getText())
        print('其他綜合損益（稅後）'+item.find_all('td')[12].getText())
        print('合併前非屬共同控制股權綜合損益淨額'+item.find_all('td')[13].getText())
        print('本期綜合損益總額（稅後）'+item.find_all('td')[14].getText())
        print('淨利（損）歸屬於母公司業主'+item.find_all('td')[15].getText())
        print('淨利（損）歸屬於共同控制下前手權益'+item.find_all('td')[16].getText())
        print('淨利（損）歸屬於非控制權益'+item.find_all('td')[17].getText())
        print('綜合損益總額歸屬於母公司業主'+item.find_all('td')[18].getText())
        print('綜合損益總額歸屬於共同控制下前手權益'+item.find_all('td')[19].getText())
        print('綜合損益總額歸屬於非控制權益'+item.find_all('td')[20].getText())
        print('基本每股盈餘（元）'+item.find_all('td')[21].getText())

    trs2 = tables[1].find_all('tr')
    for item in trs2[1:]:
        print('公司代號'+item.find_all('td')[0].getText())
        print('公司名稱'+item.find_all('td')[1].getText())
        print('收益'+item.find_all('td')[2].getText())
        print('支出及費用'+item.find_all('td')[3].getText())
        print('營業利益'+item.find_all('td')[4].getText())
        print('營業外損益'+item.find_all('td')[5].getText())
        print('稅前淨利（淨損）'+item.find_all('td')[6].getText())
        print('所得稅費用（利益）'+item.find_all('td')[7].getText())
        print('繼續營業單位本期稅後淨利（淨損）'+item.find_all('td')[8].getText())
        print('停業單位損益'+item.find_all('td')[9].getText())
        print('合併前非屬共同控制股權損益'+item.find_all('td')[10].getText())
        print('本期淨利（淨損）'+item.find_all('td')[11].getText())
        print('本期其他綜合損益（稅後淨額）'+item.find_all('td')[12].getText())
        print('合併前非屬共同控制股權綜合損益淨額'+item.find_all('td')[13].getText())
        print('本期綜合損益總額'+item.find_all('td')[14].getText())
        print('淨利（損）歸屬於母公司業主'+item.find_all('td')[15].getText())
        print('淨利（淨損）歸屬於共同控制下前手權益'+item.find_all('td')[16].getText())
        print('淨利（損）歸屬於非控制權益'+item.find_all('td')[17].getText())
        print('綜合損益總額歸屬於母公司業主'+item.find_all('td')[18].getText())
        print('綜合損益總額歸屬於共同控制下前手權益'+item.find_all('td')[19].getText())
        print('綜合損益總額歸屬於非控制權益'+item.find_all('td')[20].getText())
        print('基本每股盈餘（元）'+item.find_all('td')[21].getText())

    trs3 = tables[2].find_all('tr')
    for item in trs3[1:]:
        print('公司代號'+item.find_all('td')[0].getText())
        print('公司名稱'+item.find_all('td')[1].getText())
        print('營業收入'+item.find_all('td')[2].getText())
        print('營業成本'+item.find_all('td')[3].getText())
        print('原始認列生物資產及農產品之利益（損失）'+item.find_all('td')[4].getText())
        print('生物資產當期公允價值減出售成本之變動利益（損失）'+item.find_all('td')[5].getText())
        print('營業毛利（毛損）'+item.find_all('td')[6].getText())
        print('未實現銷貨（損）益'+item.find_all('td')[7].getText())
        print('已實現銷貨（損）益'+item.find_all('td')[8].getText())
        print('營業毛利（毛損）淨額'+item.find_all('td')[9].getText())
        print('營業費用'+item.find_all('td')[10].getText())
        print('其他收益及費損淨額'+item.find_all('td')[11].getText())
        print('營業利益（損失）'+item.find_all('td')[12].getText())
        print('營業外收入及支出'+item.find_all('td')[13].getText())
        print('稅前淨利（淨損）'+item.find_all('td')[14].getText())
        print('所得稅費用（利益）'+item.find_all('td')[15].getText())
        print('繼續營業單位本期淨利（淨損）'+item.find_all('td')[16].getText())
        print('停業單位損益'+item.find_all('td')[17].getText())
        print('合併前非屬共同控制股權損益'+item.find_all('td')[18].getText())
        print('本期淨利（淨損）'+item.find_all('td')[19].getText())
        print('其他綜合損益（淨額）'+item.find_all('td')[20].getText())
        print('合併前非屬共同控制股權綜合損益淨額'+item.find_all('td')[21].getText())
        print('本期綜合損益總額'+item.find_all('td')[22].getText())
        print('淨利（淨損）歸屬於母公司業主'+item.find_all('td')[23].getText())
        print('淨利（淨損）歸屬於共同控制下前手權益'+item.find_all('td')[24].getText())
        print('淨利（淨損）歸屬於非控制權益'+item.find_all('td')[25].getText())
        print('綜合損益總額歸屬於母公司業主'+item.find_all('td')[26].getText())
        print('綜合損益總額歸屬於共同控制下前手權益'+item.find_all('td')[27].getText())
        print('綜合損益總額歸屬於非控制權益'+item.find_all('td')[28].getText())
        print('基本每股盈餘（元）'+item.find_all('td')[29].getText())
    
    trs4 = tables[3].find_all('tr')
    for item in trs4[1:]:
        print('公司代號'+item.find_all('td')[0].getText())
        print('公司名稱'+item.find_all('td')[1].getText())
        print('利息淨收益'+item.find_all('td')[2].getText())
        print('利息以外淨收益'+item.find_all('td')[3].getText())
        print('淨收益'+item.find_all('td')[4].getText())
        print('呆帳費用、承諾及保證責任準備提存'+item.find_all('td')[5].getText())
        print('保險負債準備淨變動'+item.find_all('td')[6].getText())
        print('營業費用'+item.find_all('td')[7].getText())
        print('繼續營業單位稅前損益'+item.find_all('td')[8].getText())
        print('所得稅（費用）利益'+item.find_all('td')[9].getText())
        print('繼續營業單位本期淨利（淨損）'+item.find_all('td')[10].getText())
        print('停業單位損益'+item.find_all('td')[11].getText())
        print('本期稅後淨利（淨損）'+item.find_all('td')[12].getText())
        print('本期其他綜合損益（稅後淨額）'+item.find_all('td')[13].getText())
        print('本期綜合損益總額'+item.find_all('td')[14].getText())
        print('淨利（淨損）歸屬於母公司業主'+item.find_all('td')[15].getText())
        print('淨利（淨損）歸屬於共同控制下前手權益'+item.find_all('td')[16].getText())
        print('淨利（淨損）歸屬於非控制權益'+item.find_all('td')[17].getText())
        print('綜合損益總額歸屬於母公司業主'+item.find_all('td')[18].getText())
        print('綜合損益總額歸屬於共同控制下前手權益'+item.find_all('td')[19].getText())
        print('綜合損益總額歸屬於非控制權益'+item.find_all('td')[20].getText())
        print('基本每股盈餘（元）'+item.find_all('td')[21].getText())
        
    trs5 = tables[4].find_all('tr')
    for item in trs5[1:]:
        print('公司代號'+item.find_all('td')[0].getText())
        print('公司名稱'+item.find_all('td')[1].getText())
        print('營業收入'+item.find_all('td')[2].getText())
        print('營業成本'+item.find_all('td')[3].getText())
        print('營業費用'+item.find_all('td')[4].getText())
        print('營業利益（損失）'+item.find_all('td')[5].getText())
        print('營業外收入及支出'+item.find_all('td')[6].getText())
        print('繼續營業單位稅前純益（純損）'+item.find_all('td')[7].getText())
        print('所得稅費用（利益）'+item.find_all('td')[8].getText())
        print('繼續營業單位本期純益（純損）'+item.find_all('td')[9].getText())
        print('停業單位損益'+item.find_all('td')[10].getText())
        print('合併前非屬共同控制股權損益'+item.find_all('td')[11].getText())
        print('本期淨利（淨損）'+item.find_all('td')[12].getText())
        print('其他綜合損益（稅後淨額）'+item.find_all('td')[13].getText())
        print('合併前非屬共同控制股權綜合損益淨額'+item.find_all('td')[14].getText())
        print('本期綜合損益總額'+item.find_all('td')[15].getText())
        print('淨利（淨損）歸屬於母公司業主'+item.find_all('td')[16].getText())
        print('淨利（淨損）歸屬於共同控制下前手權益'+item.find_all('td')[17].getText())
        print('淨利（淨損）歸屬於非控制權益'+item.find_all('td')[18].getText())
        print('綜合損益總額歸屬於母公司業主'+item.find_all('td')[19].getText())
        print('綜合損益總額歸屬於共同控制下前手權益'+item.find_all('td')[20].getText())
        print('綜合損益總額歸屬於非控制權益'+item.find_all('td')[21].getText())
        print('基本每股盈餘（元）'+item.find_all('td')[22].getText())

    trs6 = tables[5].find_all('tr')
    for item in trs6[1:]:
        print('公司代號'+item.find_all('td')[0].getText())
        print('公司名稱'+item.find_all('td')[1].getText())
        print('收入'+item.find_all('td')[2].getText())
        print('支出'+item.find_all('td')[3].getText())
        print('繼續營業單位稅前淨利（淨損）'+item.find_all('td')[4].getText())
        print('所得稅費用（利益）'+item.find_all('td')[5].getText())
        print('繼續營業單位本期淨利（淨損）'+item.find_all('td')[6].getText())
        print('停業單位損益'+item.find_all('td')[7].getText())
        print('本期淨利（淨損）'+item.find_all('td')[8].getText())
        print('其他綜合損益'+item.find_all('td')[9].getText())
        print('本期綜合損益總額'+item.find_all('td')[10].getText())
        print('淨利（淨損）歸屬於母公司業主'+item.find_all('td')[11].getText())
        print('淨利（淨損）歸屬於共同控制下前手權益'+item.find_all('td')[12].getText())
        print('淨利（淨損）歸屬於非控制權益'+item.find_all('td')[13].getText())
        print('綜合損益總額歸屬於母公司業主'+item.find_all('td')[14].getText())
        print('綜合損益總額歸屬於共同控制下前手權益'+item.find_all('td')[15].getText())
        print('綜合損益總額歸屬於非控制權益'+item.find_all('td')[16].getText())
        print('基本每股盈餘（元）'+item.find_all('td')[17].getText())

#not use      
@shared_task
def crawl_all_balance_sheet():
    resp = requests.get('https://mops.twse.com.tw/mops/web/t163sb05?encodeURIComponent=1&step=1&firstin=1&off=1&isQuery=Y&TYPEK=sii&year=110&season=01')
    soup = BeautifulSoup(resp.text, 'lxml')
    print(soup.find_all('h2')[0].getText())
    tables = soup.find_all('table',{'class':'hasBorder'})

    trs1 = tables[0].find_all('tr')
    for item in trs1[1:]:
        print('公司代號'+ item.find_all('td')[0].getText().replace(' ',''))
        print('公司名稱'+ item.find_all('td')[1].getText().replace(' ',''))
        print('現金及約當現金'+ item.find_all('td')[2].getText().replace(' ',''))
        print('存放央行及拆借銀行同業'+ item.find_all('td')[3].getText().replace(' ',''))
        print('透過損益按公允價值衡量之金融資產'+ item.find_all('td')[4].getText().replace(' ',''))
        print('透過其他綜合損益按公允價值衡量之金融資產'+ item.find_all('td')[5].getText().replace(' ',''))
        print('按攤銷後成本衡量之債務工具投資'+ item.find_all('td')[6].getText().replace(' ',''))
        print('避險之衍生金融資產淨額'+ item.find_all('td')[7].getText().replace(' ',''))
        print('附賣回票券及債券投資淨額'+ item.find_all('td')[8].getText().replace(' ',''))
        print('應收款項－淨額'+ item.find_all('td')[9].getText().replace(' ',''))
        print('當期所得稅資產'+ item.find_all('td')[10].getText().replace(' ',''))
        print('待出售資產－淨額'+ item.find_all('td')[11].getText().replace(' ',''))
        print('待分配予業主之資產－淨額'+ item.find_all('td')[12].getText().replace(' ',''))
        print('貼現及放款－淨額'+ item.find_all('td')[13].getText().replace(' ',''))
        print('採用權益法之投資－淨額'+ item.find_all('td')[14].getText().replace(' ',''))
        print('受限制資產－淨額'+ item.find_all('td')[15].getText().replace(' ',''))
        print('其他金融資產－淨額'+ item.find_all('td')[16].getText().replace(' ',''))
        print('不動產及設備－淨額'+ item.find_all('td')[17].getText().replace(' ',''))
        print('使用權資產－淨額'+ item.find_all('td')[18].getText().replace(' ',''))
        print('投資性不動產投資－淨額'+ item.find_all('td')[19].getText().replace(' ',''))
        print('無形資產－淨額'+ item.find_all('td')[20].getText().replace(' ',''))
        print('遞延所得稅資產'+ item.find_all('td')[21].getText().replace(' ',''))
        print('其他資產－淨額'+ item.find_all('td')[22].getText().replace(' ',''))
        print('資產總額'+ item.find_all('td')[23].getText().replace(' ',''))
        print('央行及銀行同業存款'+ item.find_all('td')[24].getText().replace(' ',''))
        print('央行及同業融資'+ item.find_all('td')[25].getText().replace(' ',''))
        print('透過損益按公允價值衡量之金融負債'+ item.find_all('td')[26].getText().replace(' ',''))
        print('避險之衍生金融負債－淨額'+ item.find_all('td')[27].getText().replace(' ',''))
        print('附買回票券及債券負債'+ item.find_all('td')[28].getText().replace(' ',''))
        print('應付款項'+ item.find_all('td')[29].getText().replace(' ',''))
        print('當期所得稅負債'+ item.find_all('td')[30].getText().replace(' ',''))
        print('與待出售資產直接相關之負債'+ item.find_all('td')[31].getText().replace(' ',''))
        print('存款及匯款'+ item.find_all('td')[32].getText().replace(' ',''))
        print('應付金融債券'+ item.find_all('td')[33].getText().replace(' ',''))
        print('應付公司債'+ item.find_all('td')[34].getText().replace(' ',''))
        print('特別股負債'+ item.find_all('td')[35].getText().replace(' ',''))
        print('其他金融負債'+ item.find_all('td')[36].getText().replace(' ',''))
        print('負債準備'+ item.find_all('td')[37].getText().replace(' ',''))
        print('租賃負債'+ item.find_all('td')[38].getText().replace(' ',''))
        print('遞延所得稅負債'+ item.find_all('td')[39].getText().replace(' ',''))
        print('其他負債'+ item.find_all('td')[40].getText().replace(' ',''))
        print('負債總額'+ item.find_all('td')[41].getText().replace(' ',''))
        print('股本'+ item.find_all('td')[42].getText().replace(' ',''))
        print('權益─具證券性質之虛擬通貨'+ item.find_all('td')[43].getText().replace(' ',''))
        print('資本公積'+ item.find_all('td')[44].getText().replace(' ',''))
        print('保留盈餘'+ item.find_all('td')[45].getText().replace(' ',''))
        print('其他權益'+ item.find_all('td')[46].getText().replace(' ',''))
        print('庫藏股票'+ item.find_all('td')[47].getText().replace(' ',''))
        print('歸屬於母公司業主之權益合計'+ item.find_all('td')[48].getText().replace(' ',''))
        print('共同控制下前手權益'+ item.find_all('td')[49].getText().replace(' ',''))
        print('合併前非屬共同控制股權'+ item.find_all('td')[50].getText().replace(' ',''))
        print('非控制權益'+ item.find_all('td')[51].getText().replace(' ',''))
        print('權益總額'+ item.find_all('td')[52].getText().replace(' ',''))
        print('待註銷股本股數（單位：股）'+ item.find_all('td')[53].getText().replace(' ',''))
        print('母公司暨子公司所持有之母公司庫藏股股數（單位：股）'+ item.find_all('td')[54].getText().replace(' ',''))
        print('預收股款（權益項下）之約當發行股數（單位：股）'+ item.find_all('td')[55].getText().replace(' ',''))
        print('每股參考淨值'+ item.find_all('td')[56].getText().replace(' ',''))

    trs2 = tables[1].find_all('tr')
    for item in trs2[1:]:
        print('公司代號'+ item.find_all('td')[0].getText().replace(' ',''))
        print('公司名稱'+ item.find_all('td')[1].getText().replace(' ',''))
        print('流動資產'+ item.find_all('td')[2].getText().replace(' ',''))
        print('非流動資產'+ item.find_all('td')[3].getText().replace(' ',''))
        print('資產總計'+ item.find_all('td')[4].getText().replace(' ',''))
        print('流動負債'+ item.find_all('td')[5].getText().replace(' ',''))
        print('非流動負債'+ item.find_all('td')[6].getText().replace(' ',''))
        print('負債總計'+ item.find_all('td')[7].getText().replace(' ',''))
        print('股本'+ item.find_all('td')[8].getText().replace(' ',''))
        print('權益－具證券性質之虛擬通貨'+ item.find_all('td')[9].getText().replace(' ',''))
        print('資本公積'+ item.find_all('td')[10].getText().replace(' ',''))
        print('保留盈餘（或累積虧損）'+ item.find_all('td')[11].getText().replace(' ',''))
        print('其他權益'+ item.find_all('td')[12].getText().replace(' ',''))
        print('庫藏股票'+ item.find_all('td')[13].getText().replace(' ',''))
        print('歸屬於母公司業主權益合計'+ item.find_all('td')[14].getText().replace(' ',''))
        print('共同控制下前手權益'+ item.find_all('td')[15].getText().replace(' ',''))
        print('合併前非屬共同控制股權'+ item.find_all('td')[16].getText().replace(' ',''))
        print('非控制權益'+ item.find_all('td')[17].getText().replace(' ',''))
        print('權益總計'+ item.find_all('td')[18].getText().replace(' ',''))
        print('待註銷股本股數（單位：股）'+ item.find_all('td')[19].getText().replace(' ',''))
        print('預收股款（權益項下）之約當發行股數（單位：股）'+ item.find_all('td')[20].getText().replace(' ',''))
        print('母公司暨子公司持有之母公司庫藏股股數（單位：股）'+ item.find_all('td')[21].getText().replace(' ',''))
        print('每股參考淨值'+ item.find_all('td')[22].getText().replace(' ',''))

    trs3 = tables[2].find_all('tr')
    for item in trs3[1:]:
        print('公司代號'+ item.find_all('td')[0].getText().replace(' ',''))
        print('公司名稱'+ item.find_all('td')[1].getText().replace(' ',''))
        print('流動資產'+ item.find_all('td')[2].getText().replace(' ',''))
        print('非流動資產'+ item.find_all('td')[3].getText().replace(' ',''))
        print('資產總計'+ item.find_all('td')[4].getText().replace(' ',''))
        print('流動負債'+ item.find_all('td')[5].getText().replace(' ',''))
        print('非流動負債'+ item.find_all('td')[6].getText().replace(' ',''))
        print('負債總計'+ item.find_all('td')[7].getText().replace(' ',''))
        print('股本'+ item.find_all('td')[8].getText().replace(' ',''))
        print('權益－具證券性質之虛擬通貨'+ item.find_all('td')[9].getText().replace(' ',''))
        print('資本公積'+ item.find_all('td')[10].getText().replace(' ',''))
        print('保留盈餘'+ item.find_all('td')[11].getText().replace(' ',''))
        print('其他權益'+ item.find_all('td')[12].getText().replace(' ',''))
        print('庫藏股票'+ item.find_all('td')[13].getText().replace(' ',''))
        print('歸屬於母公司業主之權益合計'+ item.find_all('td')[14].getText().replace(' ',''))
        print('共同控制下前手權益'+ item.find_all('td')[15].getText().replace(' ',''))
        print('合併前非屬共同控制股權'+ item.find_all('td')[16].getText().replace(' ',''))
        print('非控制權益'+ item.find_all('td')[17].getText().replace(' ',''))
        print('權益總計'+ item.find_all('td')[18].getText().replace(' ',''))
        print('待註銷股本股數（單位：股）'+ item.find_all('td')[19].getText().replace(' ',''))
        print('預收股款（權益項下）之約當發行股數（單位：股）'+ item.find_all('td')[20].getText().replace(' ',''))
        print('母公司暨子公司所持有之母公司庫藏股股數（單位：股）'+ item.find_all('td')[21].getText().replace(' ',''))
        print('每股參考淨值'+ item.find_all('td')[22].getText().replace(' ',''))

    trs4 = tables[3].find_all('tr')
    for item in trs4[1:]:
        print('公司代號'+ item.find_all('td')[0].getText().replace(' ',''))
        print('公司名稱'+ item.find_all('td')[1].getText().replace(' ',''))
        print('現金及約當現金'+ item.find_all('td')[2].getText().replace(' ',''))
        print('存放央行及拆借金融同業'+ item.find_all('td')[3].getText().replace(' ',''))
        print('透過損益按公允價值衡量之金融資產'+ item.find_all('td')[4].getText().replace(' ',''))
        print('透過其他綜合損益按公允價值衡量之金融資產'+ item.find_all('td')[5].getText().replace(' ',''))
        print('按攤銷後成本衡量之債務工具投資'+ item.find_all('td')[6].getText().replace(' ',''))
        print('避險之衍生金融資產'+ item.find_all('td')[7].getText().replace(' ',''))
        print('附賣回票券及債券投資'+ item.find_all('td')[8].getText().replace(' ',''))
        print('應收款項－淨額'+ item.find_all('td')[9].getText().replace(' ',''))
        print('當期所得稅資產'+ item.find_all('td')[10].getText().replace(' ',''))
        print('待出售資產－淨額'+ item.find_all('td')[11].getText().replace(' ',''))
        print('貼現及放款－淨額'+ item.find_all('td')[13].getText().replace(' ',''))
        print('再保險合約資產－淨額'+ item.find_all('td')[14].getText().replace(' ',''))
        print('採用權益法之投資－淨額'+ item.find_all('td')[15].getText().replace(' ',''))
        print('受限制資產－淨額'+ item.find_all('td')[16].getText().replace(' ',''))
        print('其他金融資產－淨額'+ item.find_all('td')[17].getText().replace(' ',''))
        print('投資性不動產－淨額'+ item.find_all('td')[18].getText().replace(' ',''))
        print('不動產及設備－淨額'+ item.find_all('td')[19].getText().replace(' ',''))
        print('使用權資產－淨額'+ item.find_all('td')[20].getText().replace(' ',''))
        print('無形資產－淨額'+ item.find_all('td')[21].getText().replace(' ',''))
        print('遞延所得稅資產'+ item.find_all('td')[22].getText().replace(' ',''))
        print('其他資產－淨額'+ item.find_all('td')[23].getText().replace(' ',''))
        print('資產總額'+ item.find_all('td')[24].getText().replace(' ',''))
        print('央行及金融同業存款'+ item.find_all('td')[25].getText().replace(' ',''))
        print('央行及同業融資'+ item.find_all('td')[26].getText().replace(' ',''))
        print('透過損益按公允價值衡量之金融負債'+ item.find_all('td')[27].getText().replace(' ',''))
        print('避險之衍生金融負債'+ item.find_all('td')[28].getText().replace(' ',''))
        print('附買回票券及債券負債'+ item.find_all('td')[29].getText().replace(' ',''))
        print('應付商業本票－淨額'+ item.find_all('td')[30].getText().replace(' ',''))
        print('應付款項'+ item.find_all('td')[31].getText().replace(' ',''))
        print('當期所得稅負債'+ item.find_all('td')[32].getText().replace(' ',''))
        print('與待出售資產直接相關之負債'+ item.find_all('td')[33].getText().replace(' ',''))
        print('存款及匯款'+ item.find_all('td')[34].getText().replace(' ',''))
        print('應付債券'+ item.find_all('td')[35].getText().replace(' ',''))
        print('其他借款'+ item.find_all('td')[36].getText().replace(' ',''))
        print('特別股負債'+ item.find_all('td')[37].getText().replace(' ',''))
        print('負債準備'+ item.find_all('td')[38].getText().replace(' ',''))
        print('其他金融負債'+ item.find_all('td')[39].getText().replace(' ',''))
        print('租賃負債'+ item.find_all('td')[40].getText().replace(' ',''))
        print('遞延所得稅負債'+ item.find_all('td')[41].getText().replace(' ',''))
        print('其他負債'+ item.find_all('td')[42].getText().replace(' ',''))
        print('負債總額'+ item.find_all('td')[43].getText().replace(' ',''))
        print('股本'+ item.find_all('td')[44].getText().replace(' ',''))
        print('資本公積'+ item.find_all('td')[45].getText().replace(' ',''))
        print('保留盈餘'+ item.find_all('td')[46].getText().replace(' ',''))
        print('其他權益'+ item.find_all('td')[47].getText().replace(' ',''))
        print('庫藏股票'+ item.find_all('td')[48].getText().replace(' ',''))
        print('共同控制下前手權益'+ item.find_all('td')[49].getText().replace(' ',''))
        print('歸屬於母公司業主之權益'+ item.find_all('td')[50].getText().replace(' ',''))
        print('非控制權益'+ item.find_all('td')[51].getText().replace(' ',''))
        print('權益總額'+ item.find_all('td')[52].getText().replace(' ',''))
        print('待註銷股本股數（單位：股）'+ item.find_all('td')[53].getText().replace(' ',''))
        print('預收股款（權益項下）之約當發行股數（單位：股）'+ item.find_all('td')[54].getText().replace(' ',''))
        print('母公司暨子公司所持有之母公司庫藏股股數（單位：股）'+ item.find_all('td')[55].getText().replace(' ',''))
        print('每股參考淨值'+ item.find_all('td')[56].getText().replace(' ',''))

    trs5 = tables[4].find_all('tr')
    for item in trs5[1:]:
        print('公司代號'+ item.find_all('td')[0].getText().replace(' ',''))
        print('公司名稱'+ item.find_all('td')[1].getText().replace(' ',''))
        print('現金及約當現金'+ item.find_all('td')[2].getText().replace(' ',''))
        print('應收款項'+ item.find_all('td')[3].getText().replace(' ',''))
        print('本期所得稅資產'+ item.find_all('td')[4].getText().replace(' ',''))
        print('待出售資產'+ item.find_all('td')[5].getText().replace(' ',''))
        print('待分配予業主之資產（或處分群組）'+ item.find_all('td')[6].getText().replace(' ',''))
        print('投資'+ item.find_all('td')[7].getText().replace(' ',''))
        print('再保險合約資產'+ item.find_all('td')[8].getText().replace(' ',''))
        print('不動產及設備'+ item.find_all('td')[9].getText().replace(' ',''))
        print('使用權資產'+ item.find_all('td')[10].getText().replace(' ',''))
        print('無形資產'+ item.find_all('td')[11].getText().replace(' ',''))
        print('遞延所得稅資產'+ item.find_all('td')[12].getText().replace(' ',''))
        print('其他資產'+ item.find_all('td')[13].getText().replace(' ',''))
        print('分離帳戶保險商品資產'+ item.find_all('td')[14].getText().replace(' ',''))
        print('資產總計'+ item.find_all('td')[15].getText().replace(' ',''))
        print('短期債務'+ item.find_all('td')[16].getText().replace(' ',''))
        print('應付款項'+ item.find_all('td')[17].getText().replace(' ',''))
        print('本期所得稅負債'+ item.find_all('td')[18].getText().replace(' ',''))
        print('與待出售資產直接相關之負債'+ item.find_all('td')[19].getText().replace(' ',''))
        print('透過損益按公允價值衡量之金融負債'+ item.find_all('td')[20].getText().replace(' ',''))
        print('避險之衍生金融負債'+ item.find_all('td')[21].getText().replace(' ',''))
        print('應付債券'+ item.find_all('td')[22].getText().replace(' ',''))
        print('特別股負債'+ item.find_all('td')[23].getText().replace(' ',''))
        print('其他金融負債'+ item.find_all('td')[24].getText().replace(' ',''))
        print('租賃負債'+ item.find_all('td')[25].getText().replace(' ',''))
        print('保險負債'+ item.find_all('td')[26].getText().replace(' ',''))
        print('具金融商品性質之保險契約準備'+ item.find_all('td')[27].getText().replace(' ',''))
        print('外匯價格變動準備'+ item.find_all('td')[28].getText().replace(' ',''))
        print('負債準備'+ item.find_all('td')[29].getText().replace(' ',''))
        print('遞延所得稅負債'+ item.find_all('td')[30].getText().replace(' ',''))
        print('其他負債'+ item.find_all('td')[31].getText().replace(' ',''))
        print('分離帳戶保險商品負債'+ item.find_all('td')[32].getText().replace(' ',''))
        print('負債總計'+ item.find_all('td')[33].getText().replace(' ',''))
        print('股本'+ item.find_all('td')[34].getText().replace(' ',''))
        print('權益─具證券性質之虛擬通貨'+ item.find_all('td')[35].getText().replace(' ',''))
        print('資本公積'+ item.find_all('td')[36].getText().replace(' ',''))
        print('保留盈餘'+ item.find_all('td')[37].getText().replace(' ',''))
        print('其他權益'+ item.find_all('td')[38].getText().replace(' ',''))
        print('庫藏股票'+ item.find_all('td')[39].getText().replace(' ',''))
        print('歸屬於母公司業主之權益合計'+ item.find_all('td')[40].getText().replace(' ',''))
        print('共同控制下前手權益'+ item.find_all('td')[41].getText().replace(' ',''))
        print('合併前非屬共同控制股權'+ item.find_all('td')[42].getText().replace(' ',''))
        print('非控制權益'+ item.find_all('td')[43].getText().replace(' ',''))
        print('權益總計'+ item.find_all('td')[44].getText().replace(' ',''))
        print('待註銷股本股數（單位：股）'+ item.find_all('td')[45].getText().replace(' ',''))
        print('母公司暨子公司所持有之母公司庫藏股股數（單位：股）'+ item.find_all('td')[46].getText().replace(' ',''))
        print('預收股款（權益項下）之約當發行股數（單位：股）'+ item.find_all('td')[47].getText().replace(' ',''))
        print('每股參考淨值'+ item.find_all('td')[48].getText().replace(' ',''))

    trs6 = tables[5].find_all('tr')
    for item in trs6[1:]:
        print('公司代號'+ item.find_all('td')[0].getText().replace(' ',''))
        print('公司名稱'+ item.find_all('td')[1].getText().replace(' ',''))
        print('流動資產'+ item.find_all('td')[2].getText().replace(' ',''))
        print('非流動資產'+ item.find_all('td')[3].getText().replace(' ',''))
        print('資產總計'+ item.find_all('td')[4].getText().replace(' ',''))
        print('流動負債'+ item.find_all('td')[5].getText().replace(' ',''))
        print('非流動負債'+ item.find_all('td')[6].getText().replace(' ',''))
        print('負債總計'+ item.find_all('td')[7].getText().replace(' ',''))
        print('股本'+ item.find_all('td')[8].getText().replace(' ',''))
        print('權益－具證券性質之虛擬通貨'+ item.find_all('td')[9].getText().replace(' ',''))
        print('資本公積'+ item.find_all('td')[10].getText().replace(' ',''))
        print('保留盈餘'+ item.find_all('td')[11].getText().replace(' ',''))
        print('其他權益'+ item.find_all('td')[12].getText().replace(' ',''))
        print('庫藏股票'+ item.find_all('td')[13].getText().replace(' ',''))
        print('歸屬於母公司業主之權益合計'+ item.find_all('td')[14].getText().replace(' ',''))
        print('共同控制下前手權益'+ item.find_all('td')[15].getText().replace(' ',''))
        print('非控制權益'+ item.find_all('td')[16].getText().replace(' ',''))
        print('權益總額'+ item.find_all('td')[17].getText().replace(' ',''))
        print('待註銷股本股數（單位：股）'+ item.find_all('td')[18].getText().replace(' ',''))
        print('預收股款（權益項下）之約當發行股數（單位：股）'+ item.find_all('td')[19].getText().replace(' ',''))
        print('母公司暨子公司所持有之母公司庫藏股股數（單位：股）'+ item.find_all('td')[20].getText().replace(' ',''))
        print('每股參考淨值'+ item.find_all('td')[21].getText().replace(' ',''))

@shared_task
def add(x, y):
    print("hello world")
    print(x+y)
    return x + y

@shared_task
def mapping_category_to_index():
    categories = Category.objects.all()
    for category in categories:
        for item in Index.objects.all():
            if category.name.replace('工業', '').replace('事業', '').replace('業', '') in item.name:
                category.index = item
                category.save()